
Create table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD]
(
	[ID_CARACTERIZACION_COMUNIDAD] Integer Identity(1,1) NOT NULL,
	[ID_RYR_COMUNIDAD] Integer NOT NULL,
Primary Key ([ID_CARACTERIZACION_COMUNIDAD])
) 
go

Create table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR]
(
	[ID_CARACTERIZACION_COMUNIDAD_HOGAR] Integer Identity(1,1) NOT NULL,
	[ID_CARACTERIZACION_COMUNIDAD] Integer NOT NULL,
	[ID_CONFORMAICON_HOGAR] Integer NOT NULL,
Primary Key ([ID_CARACTERIZACION_COMUNIDAD_HOGAR])
) 
go

Create table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_DETALLE]
(
	[ID_CARACTERIZACION_COMUNIDAD] Integer NOT NULL,
	[PER_INTENCIONALIDAD] Varchar(100) NULL,
	[PER_CORREO] Varchar(100) NULL,
	[ID_ENTIDAD] Integer NULL,
	[INTENCIONALIDAD_RAZONES] Varchar(8000) NULL,
	[INTENCIONALIDAD_MANIFESTACION] Varchar(8000) NULL,
	[CONDICIONES_ACTUALES_CARACTERISTICAS] Varchar(8000) NULL,
	[CONDICIONES_ACTUALES_ACTIVIDADES] Varchar(8000) NULL,
	[ESTADO_COMUNIDAD_MUJERES_EMBARAZO] Integer NULL,
	[ESTADO_COMUNIDAD_PERSONAS_ENFERMEDAD_RUINOSA] Integer NULL,
Primary Key ([ID_CARACTERIZACION_COMUNIDAD])
) 
go

Create table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR_PERSONA]
(
	[ID_CARACTERIZACION_COMUNIDAD_HOGAR] Integer NOT NULL,
	[ID_PERSONA] Integer NOT NULL,
	[REUNIFICACION_FAMILIAR] Bit NULL,
	[ATENCION_PSICOSOCIAL] Bit NULL,
Primary Key ([ID_CARACTERIZACION_COMUNIDAD_HOGAR],[ID_PERSONA])
) 
go


Alter table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR] add  foreign key([ID_CARACTERIZACION_COMUNIDAD]) references [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD] ([ID_CARACTERIZACION_COMUNIDAD])  on update no action on delete no action 
go
Alter table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_DETALLE] add  foreign key([ID_CARACTERIZACION_COMUNIDAD]) references [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD] ([ID_CARACTERIZACION_COMUNIDAD])  on update no action on delete no action 
go
Alter table [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR_PERSONA] add  foreign key([ID_CARACTERIZACION_COMUNIDAD_HOGAR]) references [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR] ([ID_CARACTERIZACION_COMUNIDAD_HOGAR])  on update no action on delete no action 
go


