USE Maariv_Desarrollo
GO

/****** Object:  Table RYR_COMUNITARIO.TB_PLAN_RYR    Script Date: 04/11/2020 21:36:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE RYR_COMUNITARIO.TB_PLAN_RYR(
	ID_PLAN_RYR int IDENTITY(1,1) NOT NULL,
	ID_RYR_COMUNIDAD int NOT NULL,
	FECHA_MEDICION smalldatetime NULL,
	ID_TERRITORIAL int NULL,
	ID_MUNICIPIO int NULL,
	ID_ENTORNO int NULL,
	DIRECCION varchar(400) NULL,
	PROFESIONAL varchar(400) NULL,
	CORREO varchar(100) NULL,
	FECHA_ACTA_CTJT smalldatetime NULL,
	ID_ESTADO_PLAN_RYR int NULL,
	USUARIO_CREACION int NULL,
	FECHA_CREACION smalldatetime NULL,
	USUARIO_MODIFICA int NULL,
	FECHA_MODIFICA smalldatetime NULL,
	ID_DEPARTAMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID_PLAN_RYR ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY
) ON PRIMARY
GO

ALTER TABLE RYR_COMUNITARIO.TB_PLAN_RYR  WITH CHECK ADD  CONSTRAINT FK_TB_PLAN_RYR_COMUNIDADES FOREIGN KEY(ID_RYR_COMUNIDAD)
REFERENCES dbo.RYR_COMUNIDADES (ID_RYR_COMUNIDAD)
GO

ALTER TABLE RYR_COMUNITARIO.TB_PLAN_RYR CHECK CONSTRAINT FK_TB_PLAN_RYR_COMUNIDADES
GO


