IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'RYR_COMUNITARIO')
BEGIN
	EXEC('CREATE SCHEMA RYR_COMUNITARIO')
END
GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES
AS
BEGIN
	SET NOCOUNT ON
	SELECT E.ID_ENTIDAD,TE.ID_TIPO_ENTIDAD, TE.TIPO_ENTIDAD,EA.ID_ALCANCE, EA.ALCANCE,
	CASE 
				WHEN D.DAN_CDEPARTAMENTO = '0 SELECCIONE' THEN E.NOMBRE_ENTIDAD
				WHEN D.DAN_CDEPARTAMENTO IS NOT NULL THEN CONCAT( E.NOMBRE_ENTIDAD ,' - ', D.DAN_CDEPARTAMENTO, ' - ', D.DAN_CMUNICIPIO)
				ELSE E.NOMBRE_ENTIDAD END AS NOMBRE_ENTIDAD	
	FROM dbo.ENTIDAD AS E	
	INNER JOIN dbo.TIPO_ENTIDAD	TE ON E.ID_TIPO_ENTIDAD	= TE.ID_TIPO_ENTIDAD
	INNER JOIN dbo.ENTIDAD_ALCANCE	EA ON E.ID_ALCANCE	= EA.ID_ALCANCE
	LEFT JOIN dbo.V_DEPARTAMENTOS V ON V.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO						
	LEFT JOIN dbo.TBL_RDANE	D ON D.DAN_CCOD_DEPARTAMENTO = V.ID_DEPARTAMENTO AND D.DAN_NID = E.ID_MUNICIPIO
	WHERE ID_ESTADO_ENTIDAD = 1
	ORDER BY EA.ID_ALCANCE DESC,E.NOMBRE_ENTIDAD ASC
	SET NOCOUNT OFF
END
go
IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
	(
	ID_PLAN_ACCION_TRASLADO int NOT NULL IDENTITY (1, 1),
	ID_COMUNIDAD int NULL,
	TOTAL_HOGARES_TRASLADAR INT,
	TOTAL_PERSONAS_TRASLADAR INT,
	TOTAL_PERSONAS_TRASLADAR_RUV INT,
	ID_MUNICIPIO_SALIDA INT,
	ID_MUNICIPIO_LLEGADA INT,
	ID_ENTORNO_SALIDA INT,
	ID_ENTORNO_LLEGADA INT,
	CORREGIMIENTO_SALIDA VARCHAR(400),
	CORREGIMIENTO_LLEGADA VARCHAR(400)
	)  ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_ENTIDAD') 
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD
	(
	ID_PLAN_ACCION_TRASLADO int NOT NULL IDENTITY (1, 1),
	ID_ENTIDAD int NULL
	)  ON [PRIMARY]
END
SET IDENTITY_INSERT RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD ON
GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO 
@ID_COMUNIDAD INT,
@ID_PLAN_ACCION_TRASLADO INT OUT
AS
BEGIN		

	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO WHERE ID_COMUNIDAD = @ID_COMUNIDAD)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].[TB_PLAN_ACCION_TRASLADO]  ([ID_COMUNIDAD],TOTAL_HOGARES_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR_RUV ,	ID_MUNICIPIO_SALIDA ,	ID_MUNICIPIO_LLEGADA ,	ID_ENTORNO_SALIDA ,	ID_ENTORNO_LLEGADA ,	CORREGIMIENTO_SALIDA ,	CORREGIMIENTO_LLEGADA )   VALUES (@ID_COMUNIDAD,0,0,0,0,0,0,0,'COMUNIDAD SALIDA','COMUNIDAD LLEGADA')
		SET @ID_PLAN_ACCION_TRASLADO = SCOPE_IDENTITY() 
	END
	ELSE
	BEGIN
		SELECT TOP 1 @ID_PLAN_ACCION_TRASLADO = ID_PLAN_ACCION_TRASLADO FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO WHERE ID_COMUNIDAD = @ID_COMUNIDAD
	END
END
go
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_ENTIDAD INT
AS
BEGIN
	SET IDENTITY_INSERT RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD ON
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_ENTIDAD = @ID_ENTIDAD)
	BEGIN
		INSERT INTO RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD (ID_PLAN_ACCION_TRASLADO, ID_ENTIDAD) VALUES (@ID_PLAN_ACCION_TRASLADO, @ID_ENTIDAD)
	END
END
go
--SELECT * FROM RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
--SELECT * FROM RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO 
@ID_PLAN_ACCION_TRASLADO INT
AS
BEGIN
	SELECT *
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO 
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO 
END
go


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT
AS
BEGIN
	SELECT E.ID_ENTIDAD, CASE 
				WHEN D.DAN_CDEPARTAMENTO = '0 SELECCIONE' THEN E.NOMBRE_ENTIDAD
				WHEN D.DAN_CDEPARTAMENTO IS NOT NULL THEN CONCAT( E.NOMBRE_ENTIDAD ,' - ', D.DAN_CDEPARTAMENTO, ' - ', D.DAN_CMUNICIPIO)
				ELSE E.NOMBRE_ENTIDAD END AS NOMBRE_ENTIDAD	
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD AS A 
	JOIN dbo.ENTIDAD AS E	ON A.ID_ENTIDAD = E.ID_ENTIDAD
	INNER JOIN dbo.TIPO_ENTIDAD	TE ON E.ID_TIPO_ENTIDAD	= TE.ID_TIPO_ENTIDAD
	INNER JOIN dbo.ENTIDAD_ALCANCE	EA ON E.ID_ALCANCE	= EA.ID_ALCANCE
	LEFT JOIN dbo.V_DEPARTAMENTOS V ON V.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO						
	LEFT JOIN dbo.TBL_RDANE	D ON D.DAN_CCOD_DEPARTAMENTO = V.ID_DEPARTAMENTO AND D.DAN_NID = E.ID_MUNICIPIO

	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO 
END
go