IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'RYR_COMUNITARIO')
BEGIN
	EXEC('CREATE SCHEMA RYR_COMUNITARIO')
END
GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_ENTIDADES
AS
BEGIN
	SET NOCOUNT ON
	SELECT E.ID_ENTIDAD,TE.ID_TIPO_ENTIDAD, TE.TIPO_ENTIDAD,EA.ID_ALCANCE, EA.ALCANCE,
	CASE 
				WHEN D.DAN_CDEPARTAMENTO = '0 SELECCIONE' THEN E.NOMBRE_ENTIDAD
				WHEN D.DAN_CDEPARTAMENTO IS NOT NULL THEN CONCAT( E.NOMBRE_ENTIDAD ,' - ', D.DAN_CDEPARTAMENTO, ' - ', D.DAN_CMUNICIPIO)
				ELSE E.NOMBRE_ENTIDAD END AS NOMBRE_ENTIDAD	
	FROM dbo.ENTIDAD AS E	
	INNER JOIN dbo.TIPO_ENTIDAD	TE ON E.ID_TIPO_ENTIDAD	= TE.ID_TIPO_ENTIDAD
	INNER JOIN dbo.ENTIDAD_ALCANCE	EA ON E.ID_ALCANCE	= EA.ID_ALCANCE
	LEFT JOIN dbo.V_DEPARTAMENTOS V ON V.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO						
	LEFT JOIN dbo.TBL_RDANE	D ON D.DAN_CCOD_DEPARTAMENTO = V.ID_DEPARTAMENTO AND D.DAN_NID = E.ID_MUNICIPIO
	WHERE ID_ESTADO_ENTIDAD = 1
	ORDER BY EA.ID_ALCANCE DESC,E.NOMBRE_ENTIDAD ASC
	SET NOCOUNT OFF
END
go
IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
	(
	ID_PLAN_ACCION_TRASLADO int NOT NULL IDENTITY (1, 1),
	ID_COMUNIDAD int NULL,
	TOTAL_HOGARES_TRASLADAR INT,
	TOTAL_PERSONAS_TRASLADAR INT,
	TOTAL_PERSONAS_TRASLADAR_RUV INT,
	ID_MUNICIPIO_SALIDA INT,
	ID_MUNICIPIO_LLEGADA INT,
	ID_ENTORNO_SALIDA INT,
	ID_ENTORNO_LLEGADA INT,
	CORREGIMIENTO_SALIDA VARCHAR(400),
	CORREGIMIENTO_LLEGADA VARCHAR(400)
	)  ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_ENTIDAD') 
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD
	(
	ID_PLAN_ACCION_TRASLADO int NOT NULL IDENTITY (1, 1),
	ID_ENTIDAD int NULL
	)  ON [PRIMARY]
END
SET IDENTITY_INSERT RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD ON
GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_RYR_GET_TB_PLAN_ACCION_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_TB_PLAN_ACCION_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_TB_PLAN_ACCION_TRASLADO
@ID_COMUNIDAD INT
AS
BEGIN
	SET NOCOUNT ON
	select	ID_PLAN_ACCION_TRASLADO, [ID_COMUNIDAD],TOTAL_HOGARES_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR_RUV ,	ID_MUNICIPIO_SALIDA, D.DAN_CCOD_DEPARTAMENTO AS ID_DEPARTAMENTO_SALIDA ,	ID_MUNICIPIO_LLEGADA ,DL.DAN_CCOD_DEPARTAMENTO AS ID_DEPARTAMENTO_LLEGADA, 	ID_ENTORNO_SALIDA ,	ID_ENTORNO_LLEGADA ,	CORREGIMIENTO_SALIDA ,	CORREGIMIENTO_LLEGADA  
	from RYR_COMUNITARIO.[TB_PLAN_ACCION_TRASLADO] as A
	LEFT JOIN dbo.TBL_RDANE	D ON A.ID_MUNICIPIO_SALIDA = D.DAN_NID 
	LEFT JOIN dbo.TBL_RDANE	DL ON A.ID_MUNICIPIO_LLEGADA = DL.DAN_NID 
	where [ID_COMUNIDAD] = @ID_COMUNIDAD 
	SET NOCOUNT OFF
END
go


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO	
END
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO 
@ID_COMUNIDAD INT,
@TOTAL_HOGARES_TRASLADAR INT,
@TOTAL_PERSONAS_TRASLADAR INT,
@TOTAL_PERSONAS_TRASLADAR_RUV INT,
@ID_MUNICIPIO_SALIDA INT,
@ID_MUNICIPIO_LLEGADA INT,
@ID_ENTORNO_SALIDA INT,
@ID_ENTORNO_LLEGADA INT,
@CORREGIMIENTO_SALIDA VARCHAR(400),
@CORREGIMIENTO_LLEGADA VARCHAR(400),
@ID_PLAN_ACCION_TRASLADO INT OUT
AS
BEGIN		

	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO WHERE ID_COMUNIDAD = @ID_COMUNIDAD)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].[TB_PLAN_ACCION_TRASLADO]  ([ID_COMUNIDAD],TOTAL_HOGARES_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR ,	TOTAL_PERSONAS_TRASLADAR_RUV ,	ID_MUNICIPIO_SALIDA ,	ID_MUNICIPIO_LLEGADA ,	ID_ENTORNO_SALIDA ,	ID_ENTORNO_LLEGADA ,	CORREGIMIENTO_SALIDA ,	CORREGIMIENTO_LLEGADA )   VALUES (@ID_COMUNIDAD,@TOTAL_HOGARES_TRASLADAR,@TOTAL_PERSONAS_TRASLADAR,@TOTAL_PERSONAS_TRASLADAR_RUV,@ID_MUNICIPIO_SALIDA,@ID_MUNICIPIO_LLEGADA,@ID_ENTORNO_SALIDA,@ID_ENTORNO_LLEGADA,@CORREGIMIENTO_SALIDA,@CORREGIMIENTO_LLEGADA)
		SET @ID_PLAN_ACCION_TRASLADO = SCOPE_IDENTITY() 
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].[TB_PLAN_ACCION_TRASLADO]  SET TOTAL_HOGARES_TRASLADAR  = @TOTAL_HOGARES_TRASLADAR,	TOTAL_PERSONAS_TRASLADAR =@TOTAL_PERSONAS_TRASLADAR  ,	TOTAL_PERSONAS_TRASLADAR_RUV= @TOTAL_PERSONAS_TRASLADAR_RUV ,	ID_MUNICIPIO_SALIDA= @ID_MUNICIPIO_SALIDA ,	ID_MUNICIPIO_LLEGADA = @ID_MUNICIPIO_LLEGADA,	ID_ENTORNO_SALIDA= @ID_ENTORNO_SALIDA ,	ID_ENTORNO_LLEGADA= @ID_ENTORNO_LLEGADA ,	CORREGIMIENTO_SALIDA= @CORREGIMIENTO_SALIDA ,	CORREGIMIENTO_LLEGADA= @CORREGIMIENTO_LLEGADA WHERE [ID_COMUNIDAD] =@ID_COMUNIDAD
		SELECT TOP 1 @ID_PLAN_ACCION_TRASLADO = ID_PLAN_ACCION_TRASLADO FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO WHERE ID_COMUNIDAD = @ID_COMUNIDAD
	END
END
go
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_ENTIDAD INT
AS
BEGIN
	SET IDENTITY_INSERT RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD ON
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_ENTIDAD = @ID_ENTIDAD)
	BEGIN
		INSERT INTO RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD (ID_PLAN_ACCION_TRASLADO, ID_ENTIDAD) VALUES (@ID_PLAN_ACCION_TRASLADO, @ID_ENTIDAD)
	END
END
go
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_ENTIDAD INT
AS
BEGIN
	DELETE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_ENTIDAD = @ID_ENTIDAD
END
go

--SELECT * FROM RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO
--SELECT * FROM RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO 
@ID_PLAN_ACCION_TRASLADO INT
AS
BEGIN
	SELECT *
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO 
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO 
END
go


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT
AS
BEGIN
	SELECT E.ID_ENTIDAD, CASE 
				WHEN D.DAN_CDEPARTAMENTO = '0 SELECCIONE' THEN E.NOMBRE_ENTIDAD
				WHEN D.DAN_CDEPARTAMENTO IS NOT NULL THEN CONCAT( E.NOMBRE_ENTIDAD ,' - ', D.DAN_CDEPARTAMENTO, ' - ', D.DAN_CMUNICIPIO)
				ELSE E.NOMBRE_ENTIDAD END AS NOMBRE_ENTIDAD	
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ENTIDAD AS A 
	JOIN dbo.ENTIDAD AS E	ON A.ID_ENTIDAD = E.ID_ENTIDAD
	INNER JOIN dbo.TIPO_ENTIDAD	TE ON E.ID_TIPO_ENTIDAD	= TE.ID_TIPO_ENTIDAD
	INNER JOIN dbo.ENTIDAD_ALCANCE	EA ON E.ID_ALCANCE	= EA.ID_ALCANCE
	LEFT JOIN dbo.V_DEPARTAMENTOS V ON V.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO						
	LEFT JOIN dbo.TBL_RDANE	D ON D.DAN_CCOD_DEPARTAMENTO = V.ID_DEPARTAMENTO AND D.DAN_NID = E.ID_MUNICIPIO

	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO 
END
go

IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_CATEGORIA_TRASLADO') 
	DROP TABLE RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO
	(
	ID_CATEGORIA int NOT NULL IDENTITY (1, 1),
	NOMBRE VARCHAR(1000),
	ACTIVO BIT
	)  ON [PRIMARY]
END
GO

INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Espacio con líderes de la comunidad.  Objetivo: a. Validar el listado de las personas a acompañar en su proceso de retornar o reubicarse.b. Conocer de parte de ellos las necesidades actuales en el territorio a retornar o reubicar  y zonas geográficas del lugar de llegada. ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Verificacion del estado de salud de cada persona de los núcleos familiares. ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Acceso a salud en el territorio de llegada. ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Acceso a alimentación en el lugar llegada incluyendo: ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Tipo de alojamiento - concertado con la comunidad ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Medios de trasporte para el traslado de las personas o enseres (buses, camiones, mulas, lanchas)',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Rutas de acceso al lugar de llegada (terrestre, aéreo, fluvial)',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('No. de personas que acompañaran el traslado en el marco de la articulación interinstitucional',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('No. de personas que recibiran a los hogares en el marco de la articulación interinstitucional ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Alimentación previa, durtante y posterior al recorrido ',1)
INSERT INTO RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO (NOMBRE, ACTIVO) VALUES  ('Acompañamiento de la Fuerza pública previa, durante y posterior al recorrido ',1)

GO



IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_RYR_GET_CATEGORIA_TRASLADO_POR_ID_PLAN_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_CATEGORIA_TRASLADO_POR_ID_PLAN_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_CATEGORIA_TRASLADO_POR_ID_PLAN_TRASLADO
@ID_PLAN_ACCION_TRASLADO INT
AS
BEGIN
	SET NOCOUNT ON
	select	A.ID_CATEGORIA as 'N°', A.NOMBRE,B.RESULTADO,B.ACCIONES, B.OBSERVACIONES 
	from RYR_COMUNITARIO.TB_CATEGORIA_TRASLADO AS A
	LEFT OUTER JOIN  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA AS B ON A.ID_CATEGORIA = B.ID_CATEGORIA AND B.ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO
	where A.ACTIVO = 1
	SET NOCOUNT OFF
END
go
IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_CATEGORIA') 
begin
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA
end
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA
	(
	ID_CATEGORIA int ,
	ID_PLAN_ACCION_TRASLADO INT,
	ID_COMUNIDAD INT,
	RESULTADO VARCHAR(1000),
	ACCIONES VARCHAR(1000),
	OBSERVACIONES VARCHAR(1000)
	)  ON [PRIMARY]

GO


IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_TIPO_EVIDENCIA') 
	DROP TABLE RYR_COMUNITARIO.TB_TIPO_EVIDENCIA
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_TIPO_EVIDENCIA
	(
	ID_TIPO_EVIDENCIA int NOT NULL IDENTITY (1, 1),
	NOMBRE VARCHAR(1000),
	ACTIVO BIT
	)  ON [PRIMARY]
END
GO

INSERT INTO RYR_COMUNITARIO.TB_TIPO_EVIDENCIA (NOMBRE, ACTIVO) VALUES  ('Acta',1)
INSERT INTO RYR_COMUNITARIO.TB_TIPO_EVIDENCIA (NOMBRE, ACTIVO) VALUES  ('Decreto',1)
INSERT INTO RYR_COMUNITARIO.TB_TIPO_EVIDENCIA (NOMBRE, ACTIVO) VALUES  ('Otro',1)

GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_RYR_GET_TB_TIPO_EVIDENCIA') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_TB_TIPO_EVIDENCIA
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_RYR_GET_TB_TIPO_EVIDENCIA
AS
BEGIN
	SET NOCOUNT ON
	select	ID_TIPO_EVIDENCIA, NOMBRE
	from RYR_COMUNITARIO.TB_TIPO_EVIDENCIA as A
	where A.ACTIVO = 1
	SET NOCOUNT OFF
END
go

IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_CATEGORIA') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA
	(
	ID int NOT NULL IDENTITY (1, 1),
	ID_PLAN_ACCION_TRASLADO int NOT NULL,
	ID_COMUNIDAD int NULL,
	RESULTADO VARCHAR(1000),
	ACCIONES VARCHAR(1000),
	OBSERVACIONES VARCHAR(1000)
	)  ON [PRIMARY]
END
GO

IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO
ELSE
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO
	(
	ID int NOT NULL IDENTITY (1, 1),
	ID_PLAN_ACCION_TRASLADO int NOT NULL,
	ID_COMUNIDAD int NULL,
	ACTIVIDAD VARCHAR(1000),
	RESPONSABLE VARCHAR(1000),
	CUMPLIDA BIT,
	OBSERVACIONES VARCHAR(1000)
	)  ON [PRIMARY]
END
GO


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO	
END
GO
create PROCEDURE [RYR_COMUNITARIO].[SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO] 
@ID_PLAN_ACCION_TRASLADO INT ,
@ID_COMUNIDAD INT,
@ACTIVIDAD VARCHAR(1000),
@RESPONSABLE VARCHAR(1000),
@CUMPLIDA BIT,
@OBSERVACIONES VARCHAR(1000),
@ID INT
AS
BEGIN		
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO WHERE ID= @ID)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO  (ID_PLAN_ACCION_TRASLADO,	ID_COMUNIDAD,ACTIVIDAD,RESPONSABLE,CUMPLIDA,OBSERVACIONES)   VALUES (@ID_PLAN_ACCION_TRASLADO,	@ID_COMUNIDAD,@ACTIVIDAD,@RESPONSABLE,@CUMPLIDA,@OBSERVACIONES)		
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO  SET ACTIVIDAD = @ACTIVIDAD,RESPONSABLE=@RESPONSABLE,CUMPLIDA= @CUMPLIDA,OBSERVACIONES= @OBSERVACIONES  WHERE ID =@ID
	END
END



IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA	
END
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA 
	@ID_CATEGORIA INT,
	@ID_PLAN_ACCION_TRASLADO int,
	@ID_COMUNIDAD int ,
	@RESULTADO VARCHAR(1000),
	@ACCIONES VARCHAR(1000),
	@OBSERVACIONES VARCHAR(1000)
AS
BEGIN		
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO and ID_CATEGORIA =@ID_CATEGORIA)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_CATEGORIA  (ID_CATEGORIA, ID_PLAN_ACCION_TRASLADO ,ID_COMUNIDAD ,RESULTADO ,ACCIONES,OBSERVACIONES)   VALUES (@ID_CATEGORIA, @ID_PLAN_ACCION_TRASLADO ,@ID_COMUNIDAD ,@RESULTADO ,@ACCIONES,@OBSERVACIONES)
		SET @ID_PLAN_ACCION_TRASLADO = SCOPE_IDENTITY() 
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_CATEGORIA  SET RESULTADO= @RESULTADO ,ACCIONES= @ACCIONES,OBSERVACIONES =@OBSERVACIONES  WHERE ID_PLAN_ACCION_TRASLADO =@ID_PLAN_ACCION_TRASLADO and ID_CATEGORIA=@ID_CATEGORIA
	END
END
go
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO	
END
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO 
@ID_PLAN_ACCION_TRASLADO INT ,
@ID_COMUNIDAD INT,
@ACTIVIDAD VARCHAR(1000),
@RESPONSABLE VARCHAR(1000),
@CUMPLIDA BIT,
@OBSERVACIONES VARCHAR(1000),
@ID INT
AS
BEGIN		
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO WHERE ID= @ID)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO  (ID_PLAN_ACCION_TRASLADO,	ID_COMUNIDAD,ACTIVIDAD,RESPONSABLE,CUMPLIDA,OBSERVACIONES)   VALUES (@ID_PLAN_ACCION_TRASLADO,	@ID_COMUNIDAD,@ACTIVIDAD,@RESPONSABLE,@CUMPLIDA,@OBSERVACIONES)		
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO  SET ACTIVIDAD = @ACTIVIDAD,RESPONSABLE=@RESPONSABLE,CUMPLIDA= @CUMPLIDA,OBSERVACIONES= OBSERVACIONES  WHERE ID =@ID
	END
END
go


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO') AND type IN (N'P', N'PC')) 
	DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO 
	@ID_PLAN_ACCION_TRASLADO int
AS
BEGIN		
	SELECT ID, ACTIVIDAD, RESPONSABLE, CUMPLIDA, OBSERVACIONES  
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO 
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO
	
END
go


IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_PROFESIONALES') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_PROFESIONALES

CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_PROFESIONALES
	(
	ID int NOT NULL IDENTITY (1, 1),
	ID_PLAN_ACCION_TRASLADO int,
	ID_COMUNIDAD int NULL,
	PROFESIONAL VARCHAR(400),
	ID_ENTIDAD INT,
	TELEFONO VARCHAR(10),
	CORREO_ELECTRONICO VARCHAR(100)
	)  ON [PRIMARY]

GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES	
END
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES
	@ID int ,
	@ID_PLAN_ACCION_TRASLADO int,
	@ID_COMUNIDAD int ,
	@PROFESIONAL VARCHAR(400),
	@ID_ENTIDAD INT,
	@TELEFONO VARCHAR(10),
	@CORREO_ELECTRONICO VARCHAR(100)
AS
BEGIN		
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_PROFESIONALES WHERE ID= @ID)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_PROFESIONALES  (ID_PLAN_ACCION_TRASLADO ,	ID_COMUNIDAD ,	PROFESIONAL ,	ID_ENTIDAD ,	TELEFONO ,	CORREO_ELECTRONICO )   VALUES (@ID_PLAN_ACCION_TRASLADO ,	@ID_COMUNIDAD ,	@PROFESIONAL ,	@ID_ENTIDAD ,@TELEFONO ,	@CORREO_ELECTRONICO )		
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_PROFESIONALES  SET PROFESIONAL= @PROFESIONAL ,	ID_ENTIDAD=@ID_ENTIDAD ,	TELEFONO=@TELEFONO ,	CORREO_ELECTRONICO =@CORREO_ELECTRONICO  WHERE ID =@ID
	END
END
go



IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_PROFESIONALES') AND type IN (N'P', N'PC')) 
	DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_PROFESIONALES
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_PROFESIONALES 
	@ID_PLAN_ACCION_TRASLADO int
AS
BEGIN		
	SELECT ID,PROFESIONAL ,	E.ID_ENTIDAD, E.NOMBRE_ENTIDAD ,	TELEFONO ,	CORREO_ELECTRONICO 
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_PROFESIONALES  AS A
	JOIN dbo.ENTIDAD AS E	 ON A.ID_ENTIDAD = E.ID_ENTIDAD
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO
	
END
go


IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO

CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO
	(
	ID int NOT NULL IDENTITY (1, 1),
	ID_PLAN_ACCION_TRASLADO int,
	ID_COMUNIDAD int NULL,
	FECHA_REGISTRO DATE,
	ID_DIRECCION_TERRITORIAL INT,
	ID_MUNICIPIO INT,
	DIRECCION VARCHAR(400),
	ID_ENTIDAD INT,
	PROFESIONAL_REGISTRO VARCHAR(400),
	CORREO_ELECTRONICO VARCHAR(100)
	)  ON [PRIMARY]

GO

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO') AND type IN (N'P', N'PC')) 
BEGIN
	DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO	
END
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO
	@ID int,
	@ID_PLAN_ACCION_TRASLADO int,
	@ID_COMUNIDAD int ,
	@FECHA_REGISTRO DATE,
	@ID_DIRECCION_TERRITORIAL INT,
	@ID_MUNICIPIO INT,
	@DIRECCION VARCHAR(400),
	@ID_ENTIDAD INT,
	@PROFESIONAL_REGISTRO VARCHAR(400),
	@CORREO_ELECTRONICO VARCHAR(100)
AS
BEGIN		
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO WHERE ID_PLAN_ACCION_TRASLADO= @ID_PLAN_ACCION_TRASLADO)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO  (ID_PLAN_ACCION_TRASLADO ,ID_COMUNIDAD  ,FECHA_REGISTRO ,ID_DIRECCION_TERRITORIAL ,ID_MUNICIPIO ,DIRECCION ,ID_ENTIDAD ,PROFESIONAL_REGISTRO,CORREO_ELECTRONICO )   VALUES (@ID_PLAN_ACCION_TRASLADO ,@ID_COMUNIDAD  ,@FECHA_REGISTRO ,@ID_DIRECCION_TERRITORIAL ,@ID_MUNICIPIO ,@DIRECCION ,@ID_ENTIDAD ,@PROFESIONAL_REGISTRO,@CORREO_ELECTRONICO )		
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO  SET FECHA_REGISTRO=@FECHA_REGISTRO ,ID_DIRECCION_TERRITORIAL =@ID_DIRECCION_TERRITORIAL ,ID_MUNICIPIO =@ID_MUNICIPIO ,DIRECCION =@DIRECCION ,ID_ENTIDAD =@ID_ENTIDAD ,PROFESIONAL_REGISTRO=@PROFESIONAL_REGISTRO, CORREO_ELECTRONICO=@CORREO_ELECTRONICO  WHERE ID_PLAN_ACCION_TRASLADO=@ID_PLAN_ACCION_TRASLADO
	END
END
go



IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO') AND type IN (N'P', N'PC')) 
	DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO 
	@ID_PLAN_ACCION_TRASLADO int
AS
BEGIN		
	SELECT ID,E.ID_ENTIDAD, E.NOMBRE_ENTIDAD , FECHA_REGISTRO ,ID_DIRECCION_TERRITORIAL ,A.ID_MUNICIPIO,DAN_CCOD_DEPARTAMENTO, D.DAN_CMUNICIPIO ,A.DIRECCION ,PROFESIONAL_REGISTRO,CORREO_ELECTRONICO 
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_ALISTAMIENTO  AS A
	JOIN dbo.ENTIDAD AS E	 ON A.ID_ENTIDAD = E.ID_ENTIDAD
	JOIN dbo.TBL_RDANE	D ON A.ID_MUNICIPIO = D.DAN_NID
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO
	
END
go


IF  EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR') 
	DROP TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR

CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR
	(
	ID int NOT NULL IDENTITY (1, 1),
	ID_PLAN_ACCION_TRASLADO int,
	ID_COMUNIDAD int NULL,
	ID_HOGAR int NULL,
	ESTUFAS INT NULL,
	NEVERAS INT NULL,
	UTENCILIOS_COCINA INT NULL,
	CAMAS INT NULL,
	COLCHONES INT NULL,
	COBIJAS INT NULL,
	SOFAS INT NULL,
	SILLAS INT NULL,
	MESAS INT NULL,
	EQUIPOS_DE_SONIDO INT NULL,
	JUGUTES_ROPA INT NULL,
	BICICLETAS INT NULL,
	MOTOS INT NULL,
	TULAS INT NULL,
	PESO INT NULL,
	ROTULACION BIT
	)  ON [PRIMARY]
GO


IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR
@ID_COMUNIDAD INT
AS
BEGIN
	SET NOCOUNT ON
	select CH.ID_HOGAR AS HOGAR, ISNULL(P.PER_CNOMBRE1, '') + ' ' + ISNULL( P.PER_CNOMBRE2, '') + ' ' + ISNULL(P.PER_CAPELLIDO1, '') + ' ' + ISNULL(P.PER_CAPELLIDO2, '') AS 'REPRESENTANTE_HOGAR', [TIPO_IDENTIFICACION]+ ' ' + P.PER_CCEDULA AS DOCUMENTO
	--, 	TULAS ,PESO ,ROTULACION 
	from [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD] AS C
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_DETALLE] AS D ON C.ID_CARACTERIZACION_COMUNIDAD = D.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR] AS H ON D.ID_CARACTERIZACION_COMUNIDAD = H.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR_PERSONA] AS HP ON H.ID_CARACTERIZACION_COMUNIDAD_HOGAR = HP.ID_CARACTERIZACION_COMUNIDAD_HOGAR
	JOIN [dbo].[TBL_RPERSONA] AS P ON HP.ID_PERSONA = P.ID_PERSONA 
	JOIN [dbo].[TIPO_IDENTIFICACION] AS IDE ON P.TDO_NID = IDE.ID_TIPO_IDENTIFICACION
	join [dbo].[RYR_CONFORMACION_HOGAR] as CH ON P.ID_PERSONA = CH.ID_PERSONA
	join [dbo].[TIPO_PARENTESCO] AS PAR ON CH.ID_PARENTESCO= PAR.ID_PARENTESCO
	LEFT JOIN RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR AS INV ON CH.ID_HOGAR = INV.ID_HOGAR
	WHERE PAR.ID_PARENTESCO =14--JEFE(A) DE HOGAR - AUTORIZADO
	--and C.ID_RYR_COMUNIDAD = @ID_COMUNIDAD
	order by ch.ID_HOGAR

END

go




IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_ACTUALIZAR_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR
	@ID int ,
	@ID_PLAN_ACCION_TRASLADO int,
	@ID_COMUNIDAD int ,
	@ID_HOGAR int ,
	@ESTUFAS INT ,
	@NEVERAS INT ,
	@UTENCILIOS_COCINA INT ,
	@CAMAS INT ,
	@COLCHONES INT ,
	@COBIJAS INT ,
	@SOFAS INT ,
	@SILLAS INT ,
	@MESAS INT ,
	@EQUIPOS_DE_SONIDO INT ,
	@JUGUTES_ROPA INT ,
	@BICICLETAS INT ,
	@MOTOS INT ,
	@TULAS INT ,
	@PESO INT ,
	@ROTULACION BIT
AS
BEGIN
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR WHERE ID_HOGAR =@ID_HOGAR)
	BEGIN	
		INSERT INTO [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR  (ID_PLAN_ACCION_TRASLADO ,ID_COMUNIDAD ,ID_HOGAR ,ESTUFAS,NEVERAS ,UTENCILIOS_COCINA ,CAMAS ,COLCHONES ,
																  COBIJAS ,SOFAS ,SILLAS ,MESAS ,EQUIPOS_DE_SONIDO ,JUGUTES_ROPA ,BICICLETAS ,MOTOS ,TULAS ,PESO,ROTULACION )   	
		VALUES (@ID_PLAN_ACCION_TRASLADO ,@ID_COMUNIDAD ,@ID_HOGAR ,@ESTUFAS ,@NEVERAS ,@UTENCILIOS_COCINA ,@CAMAS ,@COLCHONES ,@COBIJAS ,@SOFAS ,@SILLAS ,@MESAS ,
				@EQUIPOS_DE_SONIDO ,@JUGUTES_ROPA ,@BICICLETAS ,@MOTOS ,@TULAS ,@PESO ,@ROTULACION )
		SET @ID = SCOPE_IDENTITY() 
	END
	ELSE
	BEGIN
		UPDATE [RYR_COMUNITARIO].TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR  SET ESTUFAS=@ESTUFAS ,NEVERAS=@NEVERAS ,UTENCILIOS_COCINA=@UTENCILIOS_COCINA ,CAMAS=@CAMAS ,COLCHONES=@COLCHONES ,
																COBIJAS=@COBIJAS ,SOFAS=@SOFAS ,SILLAS=@SILLAS ,MESAS=@MESAS ,EQUIPOS_DE_SONIDO=@EQUIPOS_DE_SONIDO ,
																JUGUTES_ROPA= @JUGUTES_ROPA ,BICICLETAS=@BICICLETAS ,MOTOS= @MOTOS ,TULAS= @TULAS ,PESO=@PESO ,ROTULACION=@ROTULACION  
																FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR 
																WHERE ID_HOGAR =@ID_HOGAR
	END

END

GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR_ENSERES') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR_ENSERES
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR_ENSERES
@ID_HOGAR INT
AS
BEGIN
	SET NOCOUNT ON
	select ID_HOGAR ,ESTUFAS,NEVERAS ,UTENCILIOS_COCINA ,CAMAS ,COLCHONES ,COBIJAS ,SOFAS ,SILLAS ,MESAS ,EQUIPOS_DE_SONIDO ,JUGUTES_ROPA ,BICICLETAS ,MOTOS ,TULAS ,PESO,ROTULACION FROM RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR 
	WHERE  ID_HOGAR = @ID_HOGAR

END

go

IF NOT EXISTS (SELECT *   FROM INFORMATION_SCHEMA.TABLES   WHERE TABLE_SCHEMA = 'RYR_COMUNITARIO'   AND TABLE_NAME = 'TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD') 
BEGIN 
	CREATE TABLE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD
	(
	ID_PLAN_ACCION_TRASLADO int,
	ID_CATEGORIA int ,
	ID_ENTIDAD int 
	)  ON [PRIMARY]
END
SET IDENTITY_INSERT RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD ON
GO

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_INSERTAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_CATEGORIA int ,
@ID_ENTIDAD INT
AS
BEGIN
	IF NOT EXISTS( SELECT TOP 1 1 FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_ENTIDAD = @ID_ENTIDAD AND ID_CATEGORIA = @ID_CATEGORIA)
	BEGIN
		INSERT INTO RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD (ID_PLAN_ACCION_TRASLADO,ID_CATEGORIA, ID_ENTIDAD) VALUES (@ID_PLAN_ACCION_TRASLADO,@ID_CATEGORIA, @ID_ENTIDAD)
	END
END
go
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_CATEGORIA int ,
@ID_ENTIDAD INT
AS
BEGIN
	DELETE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_ENTIDAD = @ID_ENTIDAD AND ID_CATEGORIA =@ID_CATEGORIA
END
go

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD 
@ID_PLAN_ACCION_TRASLADO INT,
@ID_CATEGORIA int 
AS
BEGIN
	SELECT E.ID_ENTIDAD, CASE 
				WHEN D.DAN_CDEPARTAMENTO = '0 SELECCIONE' THEN E.NOMBRE_ENTIDAD
				WHEN D.DAN_CDEPARTAMENTO IS NOT NULL THEN CONCAT( E.NOMBRE_ENTIDAD ,' - ', D.DAN_CDEPARTAMENTO, ' - ', D.DAN_CMUNICIPIO)
				ELSE E.NOMBRE_ENTIDAD END AS NOMBRE_ENTIDAD	
	FROM  RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_CATEGORIA_ENTIDAD AS A 
	JOIN dbo.ENTIDAD AS E	ON A.ID_ENTIDAD = E.ID_ENTIDAD
	INNER JOIN dbo.TIPO_ENTIDAD	TE ON E.ID_TIPO_ENTIDAD	= TE.ID_TIPO_ENTIDAD
	INNER JOIN dbo.ENTIDAD_ALCANCE	EA ON E.ID_ALCANCE	= EA.ID_ALCANCE
	LEFT JOIN dbo.V_DEPARTAMENTOS V ON V.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO						
	LEFT JOIN dbo.TBL_RDANE	D ON D.DAN_CCOD_DEPARTAMENTO = V.ID_DEPARTAMENTO AND D.DAN_NID = E.ID_MUNICIPIO
	WHERE ID_PLAN_ACCION_TRASLADO = @ID_PLAN_ACCION_TRASLADO AND ID_CATEGORIA = @ID_CATEGORIA
END
go

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO
@ID INT
AS
BEGIN
	DELETE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_BALANCE_TRASLADO where ID = @ID
END
go

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_ELIMINAR_TB_PLAN_ACCION_TRASLADO_PROFESIONALES
@ID INT
AS
BEGIN
	DELETE RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_PROFESIONALES where ID = @ID
END

GO

IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_BUSQUEDA_PERSONA_POR_NUMERO_DOCUMENTO') AND type IN (N'P', N'PC')) 
DROP PROCEDURE RYR_COMUNITARIO.SP_GET_BUSQUEDA_PERSONA_POR_NUMERO_DOCUMENTO
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_BUSQUEDA_PERSONA_POR_NUMERO_DOCUMENTO
@NUMERO_DOCUMENTO varchar(100)
AS
BEGIN
	SET NOCOUNT ON
	select CH.ID_HOGAR AS HOGAR, ISNULL(P.PER_CNOMBRE1, '') + ' ' + ISNULL( P.PER_CNOMBRE2, '') + ' ' + ISNULL(P.PER_CAPELLIDO1, '') + ' ' + ISNULL(P.PER_CAPELLIDO2, '') AS 'PERSONA', [TIPO_IDENTIFICACION]+ ' ' + P.PER_CCEDULA AS DOCUMENTO
	from [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD] AS C
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_DETALLE] AS D ON C.ID_CARACTERIZACION_COMUNIDAD = D.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR] AS H ON D.ID_CARACTERIZACION_COMUNIDAD = H.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR_PERSONA] AS HP ON H.ID_CARACTERIZACION_COMUNIDAD_HOGAR = HP.ID_CARACTERIZACION_COMUNIDAD_HOGAR
	JOIN [dbo].[TBL_RPERSONA] AS P ON HP.ID_PERSONA = P.ID_PERSONA 
	JOIN [dbo].[TIPO_IDENTIFICACION] AS IDE ON P.TDO_NID = IDE.ID_TIPO_IDENTIFICACION
	join [dbo].[RYR_CONFORMACION_HOGAR] as CH ON P.ID_PERSONA = CH.ID_PERSONA
	join [dbo].[TIPO_PARENTESCO] AS PAR ON CH.ID_PARENTESCO= PAR.ID_PARENTESCO
	LEFT JOIN RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR AS INV ON CH.ID_HOGAR = INV.ID_HOGAR
	WHERE P.PER_CCEDULA = @NUMERO_DOCUMENTO
	--and C.ID_RYR_COMUNIDAD = @ID_COMUNIDAD
	order by ch.ID_HOGAR

END
GO
IF EXISTS ( SELECT  * FROM    sys.objects WHERE   object_id = OBJECT_ID(N'RYR_COMUNITARIO.SP_GET_PERSONAS_NO_SE_TRASLADAN') AND type IN (N'P', N'PC')) 
	DROP PROCEDURE RYR_COMUNITARIO.SP_GET_PERSONAS_NO_SE_TRASLADAN
GO
CREATE PROCEDURE RYR_COMUNITARIO.SP_GET_PERSONAS_NO_SE_TRASLADAN 
	@ID_PLAN_ACCION_TRASLADO int
AS
BEGIN		
	select TOP 100 CH.ID_HOGAR AS HOGAR, ISNULL(P.PER_CNOMBRE1, '') + ' ' + ISNULL( P.PER_CNOMBRE2, '') + ' ' + ISNULL(P.PER_CAPELLIDO1, '') + ' ' + ISNULL(P.PER_CAPELLIDO2, '') AS 'PERSONA', [TIPO_IDENTIFICACION]+ ' ' + P.PER_CCEDULA AS DOCUMENTO
	from [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD] AS C
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_DETALLE] AS D ON C.ID_CARACTERIZACION_COMUNIDAD = D.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR] AS H ON D.ID_CARACTERIZACION_COMUNIDAD = H.ID_CARACTERIZACION_COMUNIDAD
	JOIN [RYR_COMUNITARIO].[TB_CARACTERIZACION_COMUNIDAD_HOGAR_PERSONA] AS HP ON H.ID_CARACTERIZACION_COMUNIDAD_HOGAR = HP.ID_CARACTERIZACION_COMUNIDAD_HOGAR
	JOIN [dbo].[TBL_RPERSONA] AS P ON HP.ID_PERSONA = P.ID_PERSONA 
	JOIN [dbo].[TIPO_IDENTIFICACION] AS IDE ON P.TDO_NID = IDE.ID_TIPO_IDENTIFICACION
	join [dbo].[RYR_CONFORMACION_HOGAR] as CH ON P.ID_PERSONA = CH.ID_PERSONA
	join [dbo].[TIPO_PARENTESCO] AS PAR ON CH.ID_PARENTESCO= PAR.ID_PARENTESCO
	LEFT JOIN RYR_COMUNITARIO.TB_PLAN_ACCION_TRASLADO_INVENTARIO_HOGAR AS INV ON CH.ID_HOGAR = INV.ID_HOGAR
	--WHERE TRASLADA = 1--FALA VALIDAR ESTO
	
END
go